DATASET:
  type: NS
  sample_rate: 16000
  max_length: 3 # input snipit length
  train: train # train set folder
  dev: test # dev set folder
  eval: eval # eval set folder for tensorboard logging
  noise_folder: DEMAND # if not None, applies noise inject
  rir_folder: # if not None, applies RIR
  rir_mode: # image/direct/early
  vol_perturbed: # Tuple
  speed_perturbed: False

MODEL:
  type: ns_dparn_v0 # model-name
  
LOSS:
  sig_loss: stft_ov
  sig_threshold:

OPTIMIZER:
  gradiend_clip: 10
  lr: 0.0001
  num_epochs_decay: 0
  lr_scheduler: Plateau
  mode: min
  patience: 5
  gamma: 0.5
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.00001

TRAIN:
  num_epochs: 200
  resume_epoch:
  batch_size: 8
  multi_gpu: True
  num_workers: 10
  model_average:
  use_tensorboard: True
  model_save_dir: models
  log_dir: logs
