DATASET:
  type: NS
  sample_rate: 16000
  max_length: # input snipit length
  train: # train set folder
  dev: # dev set folder
  eval: # eval set folder for tensorboard logging
  noise_folder: # if not None, applies noise inject
  rir_folder: # if not None, applies RIR
  rir_mode: # image/direct/early
  vol_perturbed: # Tuple
  speed_perturbed: False
  perturb_frequency_response: False

MODEL:
  type: # model-name
  
LOSS:
  sig_loss: sisnr
  sig_threshold: #-30

OPTIMIZER:
  gradiend_clip: 10
  lr: 0.0001
  num_epochs_decay: 0
  lr_scheduler: Plateau
  mode: min
  patience: 5
  gamma: 0.5
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.

TRAIN:
  num_epochs: 200
  resume_epoch:
  batch_size: 24
  multi_gpu: True
  num_workers: 10
  model_average:
  use_tensorboard: True
  model_save_dir: # model save folder
  log_dir: # logging save folder