DATASET:
  type: #
  sample_rate: 16000
  max_length:
  train: # train set folder
  dev: # dev set folder
  eval: # eval set folder for tensorboard logging
  noise_folder: # if not None, applies noise inject
  rir_folder: # if not None, applies RIR
  rir_mode: # image/direct/early
  vol_perturbed: # Tuple
  speed_perturbed: False
  single_spk_prob: 0.
  inactive_training: 0.
  enroll_rule: fixed_lenth
  enroll_augment: False

MODEL:
  type: # model-name
  
LOSS:
  type: sisnr
  threshold:

OPTIMIZER:
  gradiend_clip: 10
  lr: 0.001
  num_epochs_decay: 0
  lr_scheduler: Plateau
  mode: min
  patience: 5
  gamma: 0.5
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0001

TRAIN:
  num_epochs: 200
  resume_epoch:
  contrastive_learning: False
  p_spks: 6
  p_utts: 4
  batch_size: 24
  multi_gpu: True
  num_workers: 10
  model_average:
  use_tensorboard: True
  model_save_dir: ./exp/models
  log_dir: ./exp/models/logs